"""Pydantic models for validating AI agent responses.

These schemas define the expected structure of responses from each AI agent.
They are used to parse and validate the JSON returned by the LLM, ensuring
consistent data flows through the system.
"""

from pydantic import BaseModel, Field, field_validator
from enum import Enum


# --- Code Reviewer schemas ---


class CodeReviewResult(BaseModel):
    """Result of the Code_Reviewer agent analysis."""

    fortalezas: list[str] = Field(
        ..., description="List of code strengths identified"
    )
    debilidades: list[str] = Field(
        ..., description="List of code weaknesses/improvement areas identified"
    )


# --- Ticket Generator schemas ---


class Prioridad(str, Enum):
    alta = "alta"
    media = "media"
    baja = "baja"


class Dificultad(str, Enum):
    facil = "fácil"
    media = "media"
    dificil = "difícil"


class TicketData(BaseModel):
    """A single improvement ticket generated by the Ticket_Generator agent."""

    titulo: str = Field(..., max_length=120, description="Ticket title")
    descripcion: str = Field(..., description="Detailed description of the improvement")
    prioridad: Prioridad = Field(..., description="Priority level")
    dificultad: Dificultad = Field(..., description="Difficulty level")
    tiempo_estimado_minutos: int = Field(
        ..., ge=15, le=480, description="Estimated time in minutes (15-480)"
    )


class TicketGenerationResult(BaseModel):
    """Result of the Ticket_Generator agent — exactly 3 tickets."""

    tickets: list[TicketData] = Field(..., min_length=3, max_length=3)


# --- Tech Lead schemas ---


class TechLeadResult(BaseModel):
    """Result of the Tech_Lead agent — 2 to 3 interview questions."""

    preguntas: list[str] = Field(..., min_length=2, max_length=3)


# --- Evaluator schemas ---


class EvaluationResult(BaseModel):
    """Result of the Evaluator agent — feedback and approval decision."""

    feedback: str = Field(..., max_length=3000, description="Detailed feedback")
    aprobado: bool = Field(..., description="Whether the answers are approved")
